# Generated by Django 4.2.1 on 2023-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorset',
            name='colorsetstr',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
