# Generated by Django 4.2.1 on 2023-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorset', '0002_colorset_colorsetstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
