# Generated by Django 4.2.1 on 2023-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorset', '0004_alter_colorset_color2_alter_colorset_color3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorset',
            name='color2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='colorset',
            name='color3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='colorset',
            name='color4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='colorset',
            name='color5',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
